name: public npm package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  npm-package-publication:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Authenticate with private NPM package
        run: echo -e 'quickback.co\n${{ secrets.PASSWORD  }}\nmarc@quickback.co' | npm login -e marc@quickback.co -r https://registry.npmjs.org